nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: [ '^https?://(localhost|127\.0\.0\.1|nsback\.francois-lp\.dev)(:[0-9]+)?$' ]
        allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
        allow_headers: [ 'Content-Type', 'Authorization', 'X-Requested-With' ]
        expose_headers: [ 'Link' ]
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ 'Content-Type', 'Authorization', 'X-Requested-With' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
        '^/': null
